# -*- coding: utf-8 -*-
"""Untitled2.ipynb

Automatically generated by Colaboratory.

"""

def IsPrime(n):
  for j in range(2,n):
    if n%j == 0:
      return False
  return True

IsPrime(51)

def goldbach(n):
  for p in range(2,n):
    if IsPrime(p) and IsPrime(n-p):
      return p
  return 'Congratulations, you have a counterexample'

max_p = 2
for n in range(4,501,2):
  print(n,goldbach(n))
  if max_p < goldbach(n):
    max_p = goldbach(n)
print(max_p)

def PrimesTo(n):
  L = []
  for j in range(2,n):
    if IsPrime(j):
      L.append(j)
  return L

PrimesTo(100)
